### ISSUE TITLE
Numba version mismatch 

### ISSUE THREAD

**Issue by mug2000** [shuklasaharsh/Oil-Price-Analysis-Data#6]
Number version 0.53.1 conflicts with the dependencies turicreate 6.4.1 and resampy 0.2.1
Please fix.

**Comment by shuklasaharsh** [comment]
Removed the line, Please check.

**Comment by shuklasaharsh** [comment]
The issue Won't arise anymore, It was because of a version mismatch and overlap of dependencies by both libraries. This arises is run.
```diff
pip freeze >requirements.txt
```
It is now fixed.

**Comment by shuklasaharsh** [comment]
The issue Won't arise anymore, It was because of a version mismatch and overlap of dependencies by both libraries. This arises is run.
```diff
pip freeze >requirements.txt
```
It is now fixed.
